/**
 * This class is generated by jOOQ
 */
package db.jooq;


import db.jooq.Public;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.categories_categories_id_seq</code>
	 */
	public static final Sequence<Long> CATEGORIES_CATEGORIES_ID_SEQ = new SequenceImpl<Long>("categories_categories_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.wine_master_wine_id_seq</code>
	 */
	public static final Sequence<Long> WINE_MASTER_WINE_ID_SEQ = new SequenceImpl<Long>("wine_master_wine_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.winery_winery_id_seq</code>
	 */
	public static final Sequence<Long> WINERY_WINERY_ID_SEQ = new SequenceImpl<Long>("winery_winery_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
