/**
 * This class is generated by jOOQ
 */
package db.jooq;


import db.jooq.tables.Categories;
import db.jooq.tables.CategoriesType;
import db.jooq.tables.WineMaster;
import db.jooq.tables.Winedata1;
import db.jooq.tables.Winery;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.categories
	 */
	public static final Categories CATEGORIES = db.jooq.tables.Categories.CATEGORIES;

	/**
	 * The table public.categories_type
	 */
	public static final CategoriesType CATEGORIES_TYPE = db.jooq.tables.CategoriesType.CATEGORIES_TYPE;

	/**
	 * The table public.winedata1
	 */
	public static final Winedata1 WINEDATA1 = db.jooq.tables.Winedata1.WINEDATA1;

	/**
	 * The table public.wine_master
	 */
	public static final WineMaster WINE_MASTER = db.jooq.tables.WineMaster.WINE_MASTER;

	/**
	 * The table public.winery
	 */
	public static final Winery WINERY = db.jooq.tables.Winery.WINERY;
}
