/**
 * This class is generated by jOOQ
 */
package db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriesType implements Serializable {

	private static final long serialVersionUID = -898894812;

	private final Integer categoriesTypeId;
	private final String  description;

	public CategoriesType(CategoriesType value) {
		this.categoriesTypeId = value.categoriesTypeId;
		this.description = value.description;
	}

	public CategoriesType(
		Integer categoriesTypeId,
		String  description
	) {
		this.categoriesTypeId = categoriesTypeId;
		this.description = description;
	}

	public Integer getCategoriesTypeId() {
		return this.categoriesTypeId;
	}

	public String getDescription() {
		return this.description;
	}
}
