/**
 * This class is generated by jOOQ
 */
package db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categories implements Serializable {

	private static final long serialVersionUID = -785152661;

	private final Integer categoriesId;
	private final Integer categoriesTypeId;
	private final String  description;

	public Categories(Categories value) {
		this.categoriesId = value.categoriesId;
		this.categoriesTypeId = value.categoriesTypeId;
		this.description = value.description;
	}

	public Categories(
		Integer categoriesId,
		Integer categoriesTypeId,
		String  description
	) {
		this.categoriesId = categoriesId;
		this.categoriesTypeId = categoriesTypeId;
		this.description = description;
	}

	public Integer getCategoriesId() {
		return this.categoriesId;
	}

	public Integer getCategoriesTypeId() {
		return this.categoriesTypeId;
	}

	public String getDescription() {
		return this.description;
	}
}
