/**
 * This class is generated by jOOQ
 */
package db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineMaster implements Serializable {

	private static final long serialVersionUID = -1711166457;

	private final Integer wineId;
	private final String  description;
	private final Integer typeId;
	private final Integer appellationId;
	private final Integer regionId;
	private final Integer varietalId;
	private final Integer wineryId;

	public WineMaster(WineMaster value) {
		this.wineId = value.wineId;
		this.description = value.description;
		this.typeId = value.typeId;
		this.appellationId = value.appellationId;
		this.regionId = value.regionId;
		this.varietalId = value.varietalId;
		this.wineryId = value.wineryId;
	}

	public WineMaster(
		Integer wineId,
		String  description,
		Integer typeId,
		Integer appellationId,
		Integer regionId,
		Integer varietalId,
		Integer wineryId
	) {
		this.wineId = wineId;
		this.description = description;
		this.typeId = typeId;
		this.appellationId = appellationId;
		this.regionId = regionId;
		this.varietalId = varietalId;
		this.wineryId = wineryId;
	}

	public Integer getWineId() {
		return this.wineId;
	}

	public String getDescription() {
		return this.description;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public Integer getAppellationId() {
		return this.appellationId;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public Integer getVarietalId() {
		return this.varietalId;
	}

	public Integer getWineryId() {
		return this.wineryId;
	}
}
