/**
 * This class is generated by jOOQ
 */
package db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Winery implements Serializable {

	private static final long serialVersionUID = 1651246396;

	private final Integer wineryId;
	private final String  description;

	public Winery(Winery value) {
		this.wineryId = value.wineryId;
		this.description = value.description;
	}

	public Winery(
		Integer wineryId,
		String  description
	) {
		this.wineryId = wineryId;
		this.description = description;
	}

	public Integer getWineryId() {
		return this.wineryId;
	}

	public String getDescription() {
		return this.description;
	}
}
