/**
 * This class is generated by jOOQ
 */
package dbq;


import dbq.tables.Categories;
import dbq.tables.CategoriesType;
import dbq.tables.Country;
import dbq.tables.Grape;
import dbq.tables.UserAcct;
import dbq.tables.UserCellarList;
import dbq.tables.UserProfile;
import dbq.tables.UserWineList;
import dbq.tables.UserWineReview;
import dbq.tables.Wine;
import dbq.tables.WineMaster;
import dbq.tables.WineRating;
import dbq.tables.WineRegion;
import dbq.tables.WineStyle;
import dbq.tables.WineType;
import dbq.tables.Winedata1;
import dbq.tables.Winery;
import dbq.tables.WineryBk;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.categories
	 */
	public static final Categories CATEGORIES = dbq.tables.Categories.CATEGORIES;

	/**
	 * The table public.categories_type
	 */
	public static final CategoriesType CATEGORIES_TYPE = dbq.tables.CategoriesType.CATEGORIES_TYPE;

	/**
	 * The table public.country
	 */
	public static final Country COUNTRY = dbq.tables.Country.COUNTRY;

	/**
	 * The table public.grape
	 */
	public static final Grape GRAPE = dbq.tables.Grape.GRAPE;

	/**
	 * The table public.user_acct
	 */
	public static final UserAcct USER_ACCT = dbq.tables.UserAcct.USER_ACCT;

	/**
	 * The table public.user_cellar_list
	 */
	public static final UserCellarList USER_CELLAR_LIST = dbq.tables.UserCellarList.USER_CELLAR_LIST;

	/**
	 * The table public.user_profile
	 */
	public static final UserProfile USER_PROFILE = dbq.tables.UserProfile.USER_PROFILE;

	/**
	 * The table public.user_wine_list
	 */
	public static final UserWineList USER_WINE_LIST = dbq.tables.UserWineList.USER_WINE_LIST;

	/**
	 * The table public.user_wine_review
	 */
	public static final UserWineReview USER_WINE_REVIEW = dbq.tables.UserWineReview.USER_WINE_REVIEW;

	/**
	 * The table public.wine
	 */
	public static final Wine WINE = dbq.tables.Wine.WINE;

	/**
	 * The table public.winedata1
	 */
	public static final Winedata1 WINEDATA1 = dbq.tables.Winedata1.WINEDATA1;

	/**
	 * The table public.wine_master
	 */
	public static final WineMaster WINE_MASTER = dbq.tables.WineMaster.WINE_MASTER;

	/**
	 * The table public.wine_rating
	 */
	public static final WineRating WINE_RATING = dbq.tables.WineRating.WINE_RATING;

	/**
	 * The table public.wine_region
	 */
	public static final WineRegion WINE_REGION = dbq.tables.WineRegion.WINE_REGION;

	/**
	 * The table public.winery
	 */
	public static final Winery WINERY = dbq.tables.Winery.WINERY;

	/**
	 * The table public.winery_bk
	 */
	public static final WineryBk WINERY_BK = dbq.tables.WineryBk.WINERY_BK;

	/**
	 * The table public.wine_style
	 */
	public static final WineStyle WINE_STYLE = dbq.tables.WineStyle.WINE_STYLE;

	/**
	 * The table public.wine_type
	 */
	public static final WineType WINE_TYPE = dbq.tables.WineType.WINE_TYPE;
}
