/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Country implements Serializable {

	private static final long serialVersionUID = -771714569;

	private final Integer id;
	private final String  countryName;

	public Country(Country value) {
		this.id = value.id;
		this.countryName = value.countryName;
	}

	public Country(
		Integer id,
		String  countryName
	) {
		this.id = id;
		this.countryName = countryName;
	}

	public Integer getId() {
		return this.id;
	}

	public String getCountryName() {
		return this.countryName;
	}
}
