/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Grape implements Serializable {

	private static final long serialVersionUID = -1789114987;

	private final Integer id;
	private final String  grapeName;

	public Grape(Grape value) {
		this.id = value.id;
		this.grapeName = value.grapeName;
	}

	public Grape(
		Integer id,
		String  grapeName
	) {
		this.id = id;
		this.grapeName = grapeName;
	}

	public Integer getId() {
		return this.id;
	}

	public String getGrapeName() {
		return this.grapeName;
	}
}
