/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserWineReview implements Serializable {

	private static final long serialVersionUID = 1286116653;

	private final UUID       userId;
	private final Integer    wineId;
	private final Date       reviewDate;
	private final BigDecimal rating;
	private final String     comment;
	private final Integer    intensity;
	private final Integer    sweetness;
	private final Integer    alcohol;
	private final Integer    tannin;
	private final Integer    acidity;
	private final Integer    finish;
	private final Integer    sortSeq;

	public UserWineReview(UserWineReview value) {
		this.userId = value.userId;
		this.wineId = value.wineId;
		this.reviewDate = value.reviewDate;
		this.rating = value.rating;
		this.comment = value.comment;
		this.intensity = value.intensity;
		this.sweetness = value.sweetness;
		this.alcohol = value.alcohol;
		this.tannin = value.tannin;
		this.acidity = value.acidity;
		this.finish = value.finish;
		this.sortSeq = value.sortSeq;
	}

	public UserWineReview(
		UUID       userId,
		Integer    wineId,
		Date       reviewDate,
		BigDecimal rating,
		String     comment,
		Integer    intensity,
		Integer    sweetness,
		Integer    alcohol,
		Integer    tannin,
		Integer    acidity,
		Integer    finish,
		Integer    sortSeq
	) {
		this.userId = userId;
		this.wineId = wineId;
		this.reviewDate = reviewDate;
		this.rating = rating;
		this.comment = comment;
		this.intensity = intensity;
		this.sweetness = sweetness;
		this.alcohol = alcohol;
		this.tannin = tannin;
		this.acidity = acidity;
		this.finish = finish;
		this.sortSeq = sortSeq;
	}

	public UUID getUserId() {
		return this.userId;
	}

	public Integer getWineId() {
		return this.wineId;
	}

	public Date getReviewDate() {
		return this.reviewDate;
	}

	public BigDecimal getRating() {
		return this.rating;
	}

	public String getComment() {
		return this.comment;
	}

	public Integer getIntensity() {
		return this.intensity;
	}

	public Integer getSweetness() {
		return this.sweetness;
	}

	public Integer getAlcohol() {
		return this.alcohol;
	}

	public Integer getTannin() {
		return this.tannin;
	}

	public Integer getAcidity() {
		return this.acidity;
	}

	public Integer getFinish() {
		return this.finish;
	}

	public Integer getSortSeq() {
		return this.sortSeq;
	}
}
