/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfile implements Serializable {

	private static final long serialVersionUID = 542035769;

	private final Integer userId;
	private final String  username;
	private final String  membership;
	private final String  facebook;
	private final String  wechat;
	private final String  country;
	private final String  language;
	private final String  userBio;
	private final String  url;
	private final String  avatarImageUrl;

	public UserProfile(UserProfile value) {
		this.userId = value.userId;
		this.username = value.username;
		this.membership = value.membership;
		this.facebook = value.facebook;
		this.wechat = value.wechat;
		this.country = value.country;
		this.language = value.language;
		this.userBio = value.userBio;
		this.url = value.url;
		this.avatarImageUrl = value.avatarImageUrl;
	}

	public UserProfile(
		Integer userId,
		String  username,
		String  membership,
		String  facebook,
		String  wechat,
		String  country,
		String  language,
		String  userBio,
		String  url,
		String  avatarImageUrl
	) {
		this.userId = userId;
		this.username = username;
		this.membership = membership;
		this.facebook = facebook;
		this.wechat = wechat;
		this.country = country;
		this.language = language;
		this.userBio = userBio;
		this.url = url;
		this.avatarImageUrl = avatarImageUrl;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public String getUsername() {
		return this.username;
	}

	public String getMembership() {
		return this.membership;
	}

	public String getFacebook() {
		return this.facebook;
	}

	public String getWechat() {
		return this.wechat;
	}

	public String getCountry() {
		return this.country;
	}

	public String getLanguage() {
		return this.language;
	}

	public String getUserBio() {
		return this.userBio;
	}

	public String getUrl() {
		return this.url;
	}

	public String getAvatarImageUrl() {
		return this.avatarImageUrl;
	}
}
