/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAcct implements Serializable {

	private static final long serialVersionUID = -1507699025;

	private final Integer   id;
	private final String    email;
	private final String    password;
	private final Timestamp lastLogin;
	private final Boolean   isVerified;

	public UserAcct(UserAcct value) {
		this.id = value.id;
		this.email = value.email;
		this.password = value.password;
		this.lastLogin = value.lastLogin;
		this.isVerified = value.isVerified;
	}

	public UserAcct(
		Integer   id,
		String    email,
		String    password,
		Timestamp lastLogin,
		Boolean   isVerified
	) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.lastLogin = lastLogin;
		this.isVerified = isVerified;
	}

	public Integer getId() {
		return this.id;
	}

	public String getEmail() {
		return this.email;
	}

	public String getPassword() {
		return this.password;
	}

	public Timestamp getLastLogin() {
		return this.lastLogin;
	}

	public Boolean getIsVerified() {
		return this.isVerified;
	}
}
