/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserWineList implements Serializable {

	private static final long serialVersionUID = -298041063;

	private final UUID      userId;
	private final Integer   wineId;
	private final String    listType;
	private final Integer   currentQty;
	private final Timestamp lastUpdate;
	private final Integer   sortSeq;

	public UserWineList(UserWineList value) {
		this.userId = value.userId;
		this.wineId = value.wineId;
		this.listType = value.listType;
		this.currentQty = value.currentQty;
		this.lastUpdate = value.lastUpdate;
		this.sortSeq = value.sortSeq;
	}

	public UserWineList(
		UUID      userId,
		Integer   wineId,
		String    listType,
		Integer   currentQty,
		Timestamp lastUpdate,
		Integer   sortSeq
	) {
		this.userId = userId;
		this.wineId = wineId;
		this.listType = listType;
		this.currentQty = currentQty;
		this.lastUpdate = lastUpdate;
		this.sortSeq = sortSeq;
	}

	public UUID getUserId() {
		return this.userId;
	}

	public Integer getWineId() {
		return this.wineId;
	}

	public String getListType() {
		return this.listType;
	}

	public Integer getCurrentQty() {
		return this.currentQty;
	}

	public Timestamp getLastUpdate() {
		return this.lastUpdate;
	}

	public Integer getSortSeq() {
		return this.sortSeq;
	}
}
