/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCellarList implements Serializable {

	private static final long serialVersionUID = -242800372;

	private final Integer   id;
	private final String    wineName;
	private final String    typeName;
	private final String    wineryName;
	private final String    vintage;
	private final String    styleName;
	private final String    wineImageSmall;
	private final Integer   userId;
	private final Integer   currentQty;
	private final Timestamp lastUpdate;

	public UserCellarList(UserCellarList value) {
		this.id = value.id;
		this.wineName = value.wineName;
		this.typeName = value.typeName;
		this.wineryName = value.wineryName;
		this.vintage = value.vintage;
		this.styleName = value.styleName;
		this.wineImageSmall = value.wineImageSmall;
		this.userId = value.userId;
		this.currentQty = value.currentQty;
		this.lastUpdate = value.lastUpdate;
	}

	public UserCellarList(
		Integer   id,
		String    wineName,
		String    typeName,
		String    wineryName,
		String    vintage,
		String    styleName,
		String    wineImageSmall,
		Integer   userId,
		Integer   currentQty,
		Timestamp lastUpdate
	) {
		this.id = id;
		this.wineName = wineName;
		this.typeName = typeName;
		this.wineryName = wineryName;
		this.vintage = vintage;
		this.styleName = styleName;
		this.wineImageSmall = wineImageSmall;
		this.userId = userId;
		this.currentQty = currentQty;
		this.lastUpdate = lastUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public String getWineName() {
		return this.wineName;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public String getWineryName() {
		return this.wineryName;
	}

	public String getVintage() {
		return this.vintage;
	}

	public String getStyleName() {
		return this.styleName;
	}

	public String getWineImageSmall() {
		return this.wineImageSmall;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public Integer getCurrentQty() {
		return this.currentQty;
	}

	public Timestamp getLastUpdate() {
		return this.lastUpdate;
	}
}
