/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSession implements Serializable {

	private static final long serialVersionUID = -634860890;

	private final UUID userId;
	private final UUID tokenCode;
	private final Date tokenExpire;

	public UserSession(UserSession value) {
		this.userId = value.userId;
		this.tokenCode = value.tokenCode;
		this.tokenExpire = value.tokenExpire;
	}

	public UserSession(
		UUID userId,
		UUID tokenCode,
		Date tokenExpire
	) {
		this.userId = userId;
		this.tokenCode = tokenCode;
		this.tokenExpire = tokenExpire;
	}

	public UUID getUserId() {
		return this.userId;
	}

	public UUID getTokenCode() {
		return this.tokenCode;
	}

	public Date getTokenExpire() {
		return this.tokenExpire;
	}
}
