/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VUserWishlist implements Serializable {

	private static final long serialVersionUID = -569033657;

	private final Integer    id;
	private final String     wineName;
	private final String     typeName;
	private final String     wineryName;
	private final String     vintage;
	private final String     styleName;
	private final String     wineImageSmall;
	private final UUID       userId;
	private final Timestamp  lastUpdate;
	private final Integer    sortSeq;
	private final BigDecimal rating;

	public VUserWishlist(VUserWishlist value) {
		this.id = value.id;
		this.wineName = value.wineName;
		this.typeName = value.typeName;
		this.wineryName = value.wineryName;
		this.vintage = value.vintage;
		this.styleName = value.styleName;
		this.wineImageSmall = value.wineImageSmall;
		this.userId = value.userId;
		this.lastUpdate = value.lastUpdate;
		this.sortSeq = value.sortSeq;
		this.rating = value.rating;
	}

	public VUserWishlist(
		Integer    id,
		String     wineName,
		String     typeName,
		String     wineryName,
		String     vintage,
		String     styleName,
		String     wineImageSmall,
		UUID       userId,
		Timestamp  lastUpdate,
		Integer    sortSeq,
		BigDecimal rating
	) {
		this.id = id;
		this.wineName = wineName;
		this.typeName = typeName;
		this.wineryName = wineryName;
		this.vintage = vintage;
		this.styleName = styleName;
		this.wineImageSmall = wineImageSmall;
		this.userId = userId;
		this.lastUpdate = lastUpdate;
		this.sortSeq = sortSeq;
		this.rating = rating;
	}

	public Integer getId() {
		return this.id;
	}

	public String getWineName() {
		return this.wineName;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public String getWineryName() {
		return this.wineryName;
	}

	public String getVintage() {
		return this.vintage;
	}

	public String getStyleName() {
		return this.styleName;
	}

	public String getWineImageSmall() {
		return this.wineImageSmall;
	}

	public UUID getUserId() {
		return this.userId;
	}

	public Timestamp getLastUpdate() {
		return this.lastUpdate;
	}

	public Integer getSortSeq() {
		return this.sortSeq;
	}

	public BigDecimal getRating() {
		return this.rating;
	}
}
