/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineRating implements Serializable {

	private static final long serialVersionUID = -1858389036;

	private final Integer    wineId;
	private final String     ratingType;
	private final BigDecimal rating;
	private final String     comment;

	public WineRating(WineRating value) {
		this.wineId = value.wineId;
		this.ratingType = value.ratingType;
		this.rating = value.rating;
		this.comment = value.comment;
	}

	public WineRating(
		Integer    wineId,
		String     ratingType,
		BigDecimal rating,
		String     comment
	) {
		this.wineId = wineId;
		this.ratingType = ratingType;
		this.rating = rating;
		this.comment = comment;
	}

	public Integer getWineId() {
		return this.wineId;
	}

	public String getRatingType() {
		return this.ratingType;
	}

	public BigDecimal getRating() {
		return this.rating;
	}

	public String getComment() {
		return this.comment;
	}
}
