/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineType implements Serializable {

	private static final long serialVersionUID = -618116199;

	private final Integer id;
	private final String  typeName;

	public WineType(WineType value) {
		this.id = value.id;
		this.typeName = value.typeName;
	}

	public WineType(
		Integer id,
		String  typeName
	) {
		this.id = id;
		this.typeName = typeName;
	}

	public Integer getId() {
		return this.id;
	}

	public String getTypeName() {
		return this.typeName;
	}
}
