/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineStyle implements Serializable {

	private static final long serialVersionUID = 1090255687;

	private final Integer id;
	private final String  styleName;

	public WineStyle(WineStyle value) {
		this.id = value.id;
		this.styleName = value.styleName;
	}

	public WineStyle(
		Integer id,
		String  styleName
	) {
		this.id = id;
		this.styleName = styleName;
	}

	public Integer getId() {
		return this.id;
	}

	public String getStyleName() {
		return this.styleName;
	}
}
