/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineRegion implements Serializable {

	private static final long serialVersionUID = -559939192;

	private final Integer id;
	private final String  regionName;
	private final Integer countryId;

	public WineRegion(WineRegion value) {
		this.id = value.id;
		this.regionName = value.regionName;
		this.countryId = value.countryId;
	}

	public WineRegion(
		Integer id,
		String  regionName,
		Integer countryId
	) {
		this.id = id;
		this.regionName = regionName;
		this.countryId = countryId;
	}

	public Integer getId() {
		return this.id;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public Integer getCountryId() {
		return this.countryId;
	}
}
