/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Winery implements Serializable {

	private static final long serialVersionUID = 1357699152;

	private final Integer id;
	private final String  wineryName;
	private final Integer regionId;
	private final String  description;
	private final String  websiteUrl;
	private final String  wineryImageLarge;
	private final String  wineryImageSmall;

	public Winery(Winery value) {
		this.id = value.id;
		this.wineryName = value.wineryName;
		this.regionId = value.regionId;
		this.description = value.description;
		this.websiteUrl = value.websiteUrl;
		this.wineryImageLarge = value.wineryImageLarge;
		this.wineryImageSmall = value.wineryImageSmall;
	}

	public Winery(
		Integer id,
		String  wineryName,
		Integer regionId,
		String  description,
		String  websiteUrl,
		String  wineryImageLarge,
		String  wineryImageSmall
	) {
		this.id = id;
		this.wineryName = wineryName;
		this.regionId = regionId;
		this.description = description;
		this.websiteUrl = websiteUrl;
		this.wineryImageLarge = wineryImageLarge;
		this.wineryImageSmall = wineryImageSmall;
	}

	public Integer getId() {
		return this.id;
	}

	public String getWineryName() {
		return this.wineryName;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public String getDescription() {
		return this.description;
	}

	public String getWebsiteUrl() {
		return this.websiteUrl;
	}

	public String getWineryImageLarge() {
		return this.wineryImageLarge;
	}

	public String getWineryImageSmall() {
		return this.wineryImageSmall;
	}
}
