/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Winedata1 implements Serializable {

	private static final long serialVersionUID = -188919688;

	private final String id;
	private final String id2;
	private final String wineDescription;
	private final String wineLink;
	private final String appellationId;
	private final String appellation;
	private final String regionId;
	private final String region;
	private final String varietalId;
	private final String varietal;
	private final String typeId;
	private final String type;
	private final String vineyardId;
	private final String vineyard;

	public Winedata1(Winedata1 value) {
		this.id = value.id;
		this.id2 = value.id2;
		this.wineDescription = value.wineDescription;
		this.wineLink = value.wineLink;
		this.appellationId = value.appellationId;
		this.appellation = value.appellation;
		this.regionId = value.regionId;
		this.region = value.region;
		this.varietalId = value.varietalId;
		this.varietal = value.varietal;
		this.typeId = value.typeId;
		this.type = value.type;
		this.vineyardId = value.vineyardId;
		this.vineyard = value.vineyard;
	}

	public Winedata1(
		String id,
		String id2,
		String wineDescription,
		String wineLink,
		String appellationId,
		String appellation,
		String regionId,
		String region,
		String varietalId,
		String varietal,
		String typeId,
		String type,
		String vineyardId,
		String vineyard
	) {
		this.id = id;
		this.id2 = id2;
		this.wineDescription = wineDescription;
		this.wineLink = wineLink;
		this.appellationId = appellationId;
		this.appellation = appellation;
		this.regionId = regionId;
		this.region = region;
		this.varietalId = varietalId;
		this.varietal = varietal;
		this.typeId = typeId;
		this.type = type;
		this.vineyardId = vineyardId;
		this.vineyard = vineyard;
	}

	public String getId() {
		return this.id;
	}

	public String getId2() {
		return this.id2;
	}

	public String getWineDescription() {
		return this.wineDescription;
	}

	public String getWineLink() {
		return this.wineLink;
	}

	public String getAppellationId() {
		return this.appellationId;
	}

	public String getAppellation() {
		return this.appellation;
	}

	public String getRegionId() {
		return this.regionId;
	}

	public String getRegion() {
		return this.region;
	}

	public String getVarietalId() {
		return this.varietalId;
	}

	public String getVarietal() {
		return this.varietal;
	}

	public String getTypeId() {
		return this.typeId;
	}

	public String getType() {
		return this.type;
	}

	public String getVineyardId() {
		return this.vineyardId;
	}

	public String getVineyard() {
		return this.vineyard;
	}
}
