/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wine implements Serializable {

	private static final long serialVersionUID = -772685400;

	private final Integer id;
	private final String  wineName;
	private final Integer wineTypeId;
	private final Integer wineryId;
	private final String  vintage;
	private final Integer styleId;
	private final String  wineImageLarge;
	private final String  wineImageSmall;

	public Wine(Wine value) {
		this.id = value.id;
		this.wineName = value.wineName;
		this.wineTypeId = value.wineTypeId;
		this.wineryId = value.wineryId;
		this.vintage = value.vintage;
		this.styleId = value.styleId;
		this.wineImageLarge = value.wineImageLarge;
		this.wineImageSmall = value.wineImageSmall;
	}

	public Wine(
		Integer id,
		String  wineName,
		Integer wineTypeId,
		Integer wineryId,
		String  vintage,
		Integer styleId,
		String  wineImageLarge,
		String  wineImageSmall
	) {
		this.id = id;
		this.wineName = wineName;
		this.wineTypeId = wineTypeId;
		this.wineryId = wineryId;
		this.vintage = vintage;
		this.styleId = styleId;
		this.wineImageLarge = wineImageLarge;
		this.wineImageSmall = wineImageSmall;
	}

	public Integer getId() {
		return this.id;
	}

	public String getWineName() {
		return this.wineName;
	}

	public Integer getWineTypeId() {
		return this.wineTypeId;
	}

	public Integer getWineryId() {
		return this.wineryId;
	}

	public String getVintage() {
		return this.vintage;
	}

	public Integer getStyleId() {
		return this.styleId;
	}

	public String getWineImageLarge() {
		return this.wineImageLarge;
	}

	public String getWineImageSmall() {
		return this.wineImageSmall;
	}
}
