/**
 * This class is generated by jOOQ
 */
package dbq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineryBk implements Serializable {

	private static final long serialVersionUID = -317577165;

	private final Integer wineryId;
	private final String  description;

	public WineryBk(WineryBk value) {
		this.wineryId = value.wineryId;
		this.description = value.description;
	}

	public WineryBk(
		Integer wineryId,
		String  description
	) {
		this.wineryId = wineryId;
		this.description = description;
	}

	public Integer getWineryId() {
		return this.wineryId;
	}

	public String getDescription() {
		return this.description;
	}
}
