/**
 * This class is generated by jOOQ
 */
package db.jooq.tables;


import db.jooq.Public;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriesType extends TableImpl<Record> {

	private static final long serialVersionUID = -381212249;

	/**
	 * The reference instance of <code>public.categories_type</code>
	 */
	public static final CategoriesType CATEGORIES_TYPE = new CategoriesType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.categories_type.categories_type_id</code>.
	 */
	public final TableField<Record, Integer> CATEGORIES_TYPE_ID = createField("categories_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.categories_type.description</code>.
	 */
	public final TableField<Record, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * Create a <code>public.categories_type</code> table reference
	 */
	public CategoriesType() {
		this("categories_type", null);
	}

	/**
	 * Create an aliased <code>public.categories_type</code> table reference
	 */
	public CategoriesType(String alias) {
		this(alias, CATEGORIES_TYPE);
	}

	private CategoriesType(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private CategoriesType(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoriesType as(String alias) {
		return new CategoriesType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CategoriesType rename(String name) {
		return new CategoriesType(name, null);
	}
}
