/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Country extends TableImpl<Record> {

	private static final long serialVersionUID = 834539916;

	/**
	 * The reference instance of <code>public.country</code>
	 */
	public static final Country COUNTRY = new Country();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.country.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.country.country_name</code>.
	 */
	public final TableField<Record, String> COUNTRY_NAME = createField("country_name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * Create a <code>public.country</code> table reference
	 */
	public Country() {
		this("country", null);
	}

	/**
	 * Create an aliased <code>public.country</code> table reference
	 */
	public Country(String alias) {
		this(alias, COUNTRY);
	}

	private Country(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Country(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Country as(String alias) {
		return new Country(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Country rename(String name) {
		return new Country(name, null);
	}
}
