/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfile extends TableImpl<Record> {

	private static final long serialVersionUID = 1812364640;

	/**
	 * The reference instance of <code>public.user_profile</code>
	 */
	public static final UserProfile USER_PROFILE = new UserProfile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.user_profile.user_id</code>.
	 */
	public final TableField<Record, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.user_profile.username</code>.
	 */
	public final TableField<Record, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.user_profile.membership</code>.
	 */
	public final TableField<Record, String> MEMBERSHIP = createField("membership", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.user_profile.facebook</code>.
	 */
	public final TableField<Record, String> FACEBOOK = createField("facebook", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.user_profile.wechat</code>.
	 */
	public final TableField<Record, String> WECHAT = createField("wechat", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.user_profile.country</code>.
	 */
	public final TableField<Record, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.user_profile.language</code>.
	 */
	public final TableField<Record, String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.user_profile.user_bio</code>.
	 */
	public final TableField<Record, String> USER_BIO = createField("user_bio", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.user_profile.url</code>.
	 */
	public final TableField<Record, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.user_profile.avatar_image_url</code>.
	 */
	public final TableField<Record, String> AVATAR_IMAGE_URL = createField("avatar_image_url", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>public.user_profile</code> table reference
	 */
	public UserProfile() {
		this("user_profile", null);
	}

	/**
	 * Create an aliased <code>public.user_profile</code> table reference
	 */
	public UserProfile(String alias) {
		this(alias, USER_PROFILE);
	}

	private UserProfile(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserProfile(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserProfile as(String alias) {
		return new UserProfile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserProfile rename(String name) {
		return new UserProfile(name, null);
	}
}
