/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCellarList extends TableImpl<Record> {

	private static final long serialVersionUID = 657875506;

	/**
	 * The reference instance of <code>public.user_cellar_list</code>
	 */
	public static final UserCellarList USER_CELLAR_LIST = new UserCellarList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.user_cellar_list.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.user_cellar_list.wine_name</code>.
	 */
	public final TableField<Record, String> WINE_NAME = createField("wine_name", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.user_cellar_list.type_name</code>.
	 */
	public final TableField<Record, String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.user_cellar_list.winery_name</code>.
	 */
	public final TableField<Record, String> WINERY_NAME = createField("winery_name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.user_cellar_list.vintage</code>.
	 */
	public final TableField<Record, String> VINTAGE = createField("vintage", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.user_cellar_list.style_name</code>.
	 */
	public final TableField<Record, String> STYLE_NAME = createField("style_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.user_cellar_list.wine_image_small</code>.
	 */
	public final TableField<Record, String> WINE_IMAGE_SMALL = createField("wine_image_small", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.user_cellar_list.user_id</code>.
	 */
	public final TableField<Record, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.user_cellar_list.current_qty</code>.
	 */
	public final TableField<Record, Integer> CURRENT_QTY = createField("current_qty", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.user_cellar_list.last_update</code>.
	 */
	public final TableField<Record, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>public.user_cellar_list</code> table reference
	 */
	public UserCellarList() {
		this("user_cellar_list", null);
	}

	/**
	 * Create an aliased <code>public.user_cellar_list</code> table reference
	 */
	public UserCellarList(String alias) {
		this(alias, USER_CELLAR_LIST);
	}

	private UserCellarList(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserCellarList(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarList as(String alias) {
		return new UserCellarList(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserCellarList rename(String name) {
		return new UserCellarList(name, null);
	}
}
