/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserWineList extends TableImpl<Record> {

	private static final long serialVersionUID = 431792175;

	/**
	 * The reference instance of <code>public.user_wine_list</code>
	 */
	public static final UserWineList USER_WINE_LIST = new UserWineList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.user_wine_list.user_id</code>.
	 */
	public final TableField<Record, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.user_wine_list.wine_id</code>.
	 */
	public final TableField<Record, Integer> WINE_ID = createField("wine_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.user_wine_list.list_type</code>.
	 */
	public final TableField<Record, String> LIST_TYPE = createField("list_type", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>public.user_wine_list.current_qty</code>.
	 */
	public final TableField<Record, Integer> CURRENT_QTY = createField("current_qty", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.user_wine_list.last_update</code>.
	 */
	public final TableField<Record, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>public.user_wine_list</code> table reference
	 */
	public UserWineList() {
		this("user_wine_list", null);
	}

	/**
	 * Create an aliased <code>public.user_wine_list</code> table reference
	 */
	public UserWineList(String alias) {
		this(alias, USER_WINE_LIST);
	}

	private UserWineList(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserWineList(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserWineList as(String alias) {
		return new UserWineList(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserWineList rename(String name) {
		return new UserWineList(name, null);
	}
}
