/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import java.sql.Date;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSession extends TableImpl<Record> {

	private static final long serialVersionUID = 550516228;

	/**
	 * The reference instance of <code>public.user_session</code>
	 */
	public static final UserSession USER_SESSION = new UserSession();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.user_session.user_id</code>.
	 */
	public final TableField<Record, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.user_session.token_code</code>.
	 */
	public final TableField<Record, UUID> TOKEN_CODE = createField("token_code", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>public.user_session.token_expire</code>.
	 */
	public final TableField<Record, Date> TOKEN_EXPIRE = createField("token_expire", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>public.user_session</code> table reference
	 */
	public UserSession() {
		this("user_session", null);
	}

	/**
	 * Create an aliased <code>public.user_session</code> table reference
	 */
	public UserSession(String alias) {
		this(alias, USER_SESSION);
	}

	private UserSession(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserSession(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserSession as(String alias) {
		return new UserSession(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserSession rename(String name) {
		return new UserSession(name, null);
	}
}
