/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import java.sql.Timestamp;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VUserCellarList extends TableImpl<Record> {

	private static final long serialVersionUID = -5326277;

	/**
	 * The reference instance of <code>public.v_user_cellar_list</code>
	 */
	public static final VUserCellarList V_USER_CELLAR_LIST = new VUserCellarList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.v_user_cellar_list.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.v_user_cellar_list.wine_name</code>.
	 */
	public final TableField<Record, String> WINE_NAME = createField("wine_name", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.v_user_cellar_list.type_name</code>.
	 */
	public final TableField<Record, String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.v_user_cellar_list.winery_name</code>.
	 */
	public final TableField<Record, String> WINERY_NAME = createField("winery_name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.v_user_cellar_list.vintage</code>.
	 */
	public final TableField<Record, String> VINTAGE = createField("vintage", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.v_user_cellar_list.style_name</code>.
	 */
	public final TableField<Record, String> STYLE_NAME = createField("style_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.v_user_cellar_list.wine_image_small</code>.
	 */
	public final TableField<Record, String> WINE_IMAGE_SMALL = createField("wine_image_small", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.v_user_cellar_list.user_id</code>.
	 */
	public final TableField<Record, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>public.v_user_cellar_list.current_qty</code>.
	 */
	public final TableField<Record, Integer> CURRENT_QTY = createField("current_qty", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.v_user_cellar_list.last_update</code>.
	 */
	public final TableField<Record, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.v_user_cellar_list.sort_seq</code>.
	 */
	public final TableField<Record, Integer> SORT_SEQ = createField("sort_seq", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.v_user_cellar_list</code> table reference
	 */
	public VUserCellarList() {
		this("v_user_cellar_list", null);
	}

	/**
	 * Create an aliased <code>public.v_user_cellar_list</code> table reference
	 */
	public VUserCellarList(String alias) {
		this(alias, V_USER_CELLAR_LIST);
	}

	private VUserCellarList(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private VUserCellarList(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VUserCellarList as(String alias) {
		return new VUserCellarList(alias, this);
	}

	/**
	 * Rename this table
	 */
	public VUserCellarList rename(String name) {
		return new VUserCellarList(name, null);
	}
}
