/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VUserReview extends TableImpl<Record> {

	private static final long serialVersionUID = 1570235126;

	/**
	 * The reference instance of <code>public.v_user_review</code>
	 */
	public static final VUserReview V_USER_REVIEW = new VUserReview();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.v_user_review.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.v_user_review.wine_name</code>.
	 */
	public final TableField<Record, String> WINE_NAME = createField("wine_name", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.v_user_review.type_name</code>.
	 */
	public final TableField<Record, String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.v_user_review.winery_name</code>.
	 */
	public final TableField<Record, String> WINERY_NAME = createField("winery_name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.v_user_review.vintage</code>.
	 */
	public final TableField<Record, String> VINTAGE = createField("vintage", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.v_user_review.style_name</code>.
	 */
	public final TableField<Record, String> STYLE_NAME = createField("style_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.v_user_review.wine_image_small</code>.
	 */
	public final TableField<Record, String> WINE_IMAGE_SMALL = createField("wine_image_small", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.v_user_review.user_id</code>.
	 */
	public final TableField<Record, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>public.v_user_review.review_date</code>.
	 */
	public final TableField<Record, Date> REVIEW_DATE = createField("review_date", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.v_user_review.rating</code>.
	 */
	public final TableField<Record, BigDecimal> RATING = createField("rating", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>public.v_user_review.comment</code>.
	 */
	public final TableField<Record, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.v_user_review.sort_seq</code>.
	 */
	public final TableField<Record, Integer> SORT_SEQ = createField("sort_seq", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.v_user_review</code> table reference
	 */
	public VUserReview() {
		this("v_user_review", null);
	}

	/**
	 * Create an aliased <code>public.v_user_review</code> table reference
	 */
	public VUserReview(String alias) {
		this(alias, V_USER_REVIEW);
	}

	private VUserReview(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private VUserReview(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VUserReview as(String alias) {
		return new VUserReview(alias, this);
	}

	/**
	 * Rename this table
	 */
	public VUserReview rename(String name) {
		return new VUserReview(name, null);
	}
}
