/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VUserWishlist extends TableImpl<Record> {

	private static final long serialVersionUID = -740334072;

	/**
	 * The reference instance of <code>public.v_user_wishlist</code>
	 */
	public static final VUserWishlist V_USER_WISHLIST = new VUserWishlist();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.v_user_wishlist.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.v_user_wishlist.wine_name</code>.
	 */
	public final TableField<Record, String> WINE_NAME = createField("wine_name", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.v_user_wishlist.type_name</code>.
	 */
	public final TableField<Record, String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.v_user_wishlist.winery_name</code>.
	 */
	public final TableField<Record, String> WINERY_NAME = createField("winery_name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.v_user_wishlist.vintage</code>.
	 */
	public final TableField<Record, String> VINTAGE = createField("vintage", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.v_user_wishlist.style_name</code>.
	 */
	public final TableField<Record, String> STYLE_NAME = createField("style_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.v_user_wishlist.wine_image_small</code>.
	 */
	public final TableField<Record, String> WINE_IMAGE_SMALL = createField("wine_image_small", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.v_user_wishlist.user_id</code>.
	 */
	public final TableField<Record, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>public.v_user_wishlist.last_update</code>.
	 */
	public final TableField<Record, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.v_user_wishlist.sort_seq</code>.
	 */
	public final TableField<Record, Integer> SORT_SEQ = createField("sort_seq", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.v_user_wishlist.rating</code>.
	 */
	public final TableField<Record, BigDecimal> RATING = createField("rating", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * Create a <code>public.v_user_wishlist</code> table reference
	 */
	public VUserWishlist() {
		this("v_user_wishlist", null);
	}

	/**
	 * Create an aliased <code>public.v_user_wishlist</code> table reference
	 */
	public VUserWishlist(String alias) {
		this(alias, V_USER_WISHLIST);
	}

	private VUserWishlist(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private VUserWishlist(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VUserWishlist as(String alias) {
		return new VUserWishlist(alias, this);
	}

	/**
	 * Rename this table
	 */
	public VUserWishlist rename(String name) {
		return new VUserWishlist(name, null);
	}
}
