/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VWineDetail extends TableImpl<Record> {

	private static final long serialVersionUID = -867656487;

	/**
	 * The reference instance of <code>public.v_wine_detail</code>
	 */
	public static final VWineDetail V_WINE_DETAIL = new VWineDetail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.v_wine_detail.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.v_wine_detail.wine_name</code>.
	 */
	public final TableField<Record, String> WINE_NAME = createField("wine_name", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.v_wine_detail.type_name</code>.
	 */
	public final TableField<Record, String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.v_wine_detail.winery_id</code>.
	 */
	public final TableField<Record, Integer> WINERY_ID = createField("winery_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.v_wine_detail.winery_name</code>.
	 */
	public final TableField<Record, String> WINERY_NAME = createField("winery_name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.v_wine_detail.vintage</code>.
	 */
	public final TableField<Record, String> VINTAGE = createField("vintage", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.v_wine_detail.style_name</code>.
	 */
	public final TableField<Record, String> STYLE_NAME = createField("style_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.v_wine_detail.wine_image_large</code>.
	 */
	public final TableField<Record, String> WINE_IMAGE_LARGE = createField("wine_image_large", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>public.v_wine_detail</code> table reference
	 */
	public VWineDetail() {
		this("v_wine_detail", null);
	}

	/**
	 * Create an aliased <code>public.v_wine_detail</code> table reference
	 */
	public VWineDetail(String alias) {
		this(alias, V_WINE_DETAIL);
	}

	private VWineDetail(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private VWineDetail(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VWineDetail as(String alias) {
		return new VWineDetail(alias, this);
	}

	/**
	 * Rename this table
	 */
	public VWineDetail rename(String name) {
		return new VWineDetail(name, null);
	}
}
