/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineType extends TableImpl<Record> {

	private static final long serialVersionUID = -828419930;

	/**
	 * The reference instance of <code>public.wine_type</code>
	 */
	public static final WineType WINE_TYPE = new WineType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.wine_type.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.wine_type.type_name</code>.
	 */
	public final TableField<Record, String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>public.wine_type</code> table reference
	 */
	public WineType() {
		this("wine_type", null);
	}

	/**
	 * Create an aliased <code>public.wine_type</code> table reference
	 */
	public WineType(String alias) {
		this(alias, WINE_TYPE);
	}

	private WineType(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private WineType(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineType as(String alias) {
		return new WineType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public WineType rename(String name) {
		return new WineType(name, null);
	}
}
