/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wine extends TableImpl<Record> {

	private static final long serialVersionUID = -2071593375;

	/**
	 * The reference instance of <code>public.wine</code>
	 */
	public static final Wine WINE = new Wine();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.wine.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.wine.wine_name</code>.
	 */
	public final TableField<Record, String> WINE_NAME = createField("wine_name", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.wine.wine_type_id</code>.
	 */
	public final TableField<Record, Integer> WINE_TYPE_ID = createField("wine_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.wine.winery_id</code>.
	 */
	public final TableField<Record, Integer> WINERY_ID = createField("winery_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.wine.vintage</code>.
	 */
	public final TableField<Record, String> VINTAGE = createField("vintage", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.wine.style_id</code>.
	 */
	public final TableField<Record, Integer> STYLE_ID = createField("style_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.wine.wine_image_large</code>.
	 */
	public final TableField<Record, String> WINE_IMAGE_LARGE = createField("wine_image_large", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.wine.wine_image_small</code>.
	 */
	public final TableField<Record, String> WINE_IMAGE_SMALL = createField("wine_image_small", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>public.wine</code> table reference
	 */
	public Wine() {
		this("wine", null);
	}

	/**
	 * Create an aliased <code>public.wine</code> table reference
	 */
	public Wine(String alias) {
		this(alias, WINE);
	}

	private Wine(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Wine(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Wine as(String alias) {
		return new Wine(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Wine rename(String name) {
		return new Wine(name, null);
	}
}
