/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Winedata1 extends TableImpl<Record> {

	private static final long serialVersionUID = -925693243;

	/**
	 * The reference instance of <code>public.winedata1</code>
	 */
	public static final Winedata1 WINEDATA1 = new Winedata1();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.winedata1.Id</code>.
	 */
	public final TableField<Record, String> ID = createField("Id", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Id2</code>.
	 */
	public final TableField<Record, String> ID2 = createField("Id2", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Wine_Description</code>.
	 */
	public final TableField<Record, String> WINE_DESCRIPTION = createField("Wine_Description", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Wine_Link</code>.
	 */
	public final TableField<Record, String> WINE_LINK = createField("Wine_Link", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Appellation_Id</code>.
	 */
	public final TableField<Record, String> APPELLATION_ID = createField("Appellation_Id", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Appellation</code>.
	 */
	public final TableField<Record, String> APPELLATION = createField("Appellation", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Region_Id</code>.
	 */
	public final TableField<Record, String> REGION_ID = createField("Region_Id", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Region</code>.
	 */
	public final TableField<Record, String> REGION = createField("Region", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Varietal_Id</code>.
	 */
	public final TableField<Record, String> VARIETAL_ID = createField("Varietal_Id", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Varietal</code>.
	 */
	public final TableField<Record, String> VARIETAL = createField("Varietal", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Type_Id</code>.
	 */
	public final TableField<Record, String> TYPE_ID = createField("Type_Id", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Type</code>.
	 */
	public final TableField<Record, String> TYPE = createField("Type", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Vineyard_Id</code>.
	 */
	public final TableField<Record, String> VINEYARD_ID = createField("Vineyard_Id", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * The column <code>public.winedata1.Vineyard</code>.
	 */
	public final TableField<Record, String> VINEYARD = createField("Vineyard", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

	/**
	 * Create a <code>public.winedata1</code> table reference
	 */
	public Winedata1() {
		this("winedata1", null);
	}

	/**
	 * Create an aliased <code>public.winedata1</code> table reference
	 */
	public Winedata1(String alias) {
		this(alias, WINEDATA1);
	}

	private Winedata1(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Winedata1(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Winedata1 as(String alias) {
		return new Winedata1(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Winedata1 rename(String name) {
		return new Winedata1(name, null);
	}
}
