/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineStyle extends TableImpl<Record> {

	private static final long serialVersionUID = -1910630668;

	/**
	 * The reference instance of <code>public.wine_style</code>
	 */
	public static final WineStyle WINE_STYLE = new WineStyle();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.wine_style.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.wine_style.style_name</code>.
	 */
	public final TableField<Record, String> STYLE_NAME = createField("style_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>public.wine_style</code> table reference
	 */
	public WineStyle() {
		this("wine_style", null);
	}

	/**
	 * Create an aliased <code>public.wine_style</code> table reference
	 */
	public WineStyle(String alias) {
		this(alias, WINE_STYLE);
	}

	private WineStyle(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private WineStyle(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineStyle as(String alias) {
		return new WineStyle(alias, this);
	}

	/**
	 * Rename this table
	 */
	public WineStyle rename(String name) {
		return new WineStyle(name, null);
	}
}
