/**
 * This class is generated by jOOQ
 */
package dbq.tables;


import dbq.Public;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Winery extends TableImpl<Record> {

	private static final long serialVersionUID = 1396730079;

	/**
	 * The reference instance of <code>public.winery</code>
	 */
	public static final Winery WINERY = new Winery();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>public.winery.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.winery.winery_name</code>.
	 */
	public final TableField<Record, String> WINERY_NAME = createField("winery_name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.winery.region_id</code>.
	 */
	public final TableField<Record, Integer> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.winery.description</code>.
	 */
	public final TableField<Record, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(2048), this, "");

	/**
	 * The column <code>public.winery.website_url</code>.
	 */
	public final TableField<Record, String> WEBSITE_URL = createField("website_url", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.winery.winery_image_large</code>.
	 */
	public final TableField<Record, String> WINERY_IMAGE_LARGE = createField("winery_image_large", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.winery.winery_image_small</code>.
	 */
	public final TableField<Record, String> WINERY_IMAGE_SMALL = createField("winery_image_small", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>public.winery</code> table reference
	 */
	public Winery() {
		this("winery", null);
	}

	/**
	 * Create an aliased <code>public.winery</code> table reference
	 */
	public Winery(String alias) {
		this(alias, WINERY);
	}

	private Winery(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Winery(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Winery as(String alias) {
		return new Winery(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Winery rename(String name) {
		return new Winery(name, null);
	}
}
